[package]
name = "showkey"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = { version = "0.13.2", features = ["tokio"] } # 输入设备事件；tokio 特性用于异步事件流
tokio = { version = "1.0", features = ["full"] }     # 异步运行时，用于事件循环
gtk4 = "0.11"                                        # GUI：悬浮窗口
gtk4-layer-shell = "0.8"                             # Wayland layer-shell 悬浮层
ksni = "0.3.6"
serde = { version = "1", features = ["derive"] }      # 设置序列化
toml = "0.8"                                          # 设置持久化格式
